# Generated by Django 5.0.7 on 2024-07-11 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
                ('maximum_velocity', models.CharField(max_length=100, verbose_name='max_velocity')),
                ('electrical_capacity', models.CharField(max_length=100, verbose_name='electrical_capacity')),
                ('length', models.CharField(max_length=20, verbose_name='length')),
                ('width', models.CharField(max_length=20, verbose_name='width')),
                ('height', models.CharField(max_length=20, verbose_name='height')),
                ('diameter', models.CharField(max_length=20, verbose_name='diameter')),
                ('size', models.CharField(max_length=20, verbose_name='size')),
                ('production_capacity', models.CharField(max_length=100, verbose_name='production_capacity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('category', models.ManyToManyField(related_name='product_category', to='products.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product', verbose_name='product')),
            ],
        ),
    ]
