# Generated by Django 5.0.7 on 2024-07-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='diameter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='electrical_capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='electrical_capacity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_velocity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='max_velocity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='production_capacity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='width'),
        ),
    ]
